version: "3.8"

services:
    todoDB:
        image: postgres:15-alpine
        container_name: todoDB
        restart: always
        ports:
            - "5433:5432"
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_DB=todo
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres:/var/lib/postgresql/data